### ISSUE TITLE
Testes para o RF-ExecCons comportam de maneira anômala

### ISSUE THREAD

**Issue by gustavosotnas** [ES-INF-UFG-2016-2/Sempre-UFG#78]
Os testes implementados pela @gabrielaimeeg para o RF-ExecCons (classe [`src/test/java/br/ufg/inf/servico/ExecConsTest.java`](https://github.com/ES-INF-UFG-2016-2/Sempre-UFG/blob/develop/src/test/java/br/ufg/inf/servico/ExecConsTest.java)) estão apresentando um comportamento não-determinístico. Só depois que aprovei e fiz merge do Pull Request #69 para o `develop` e comecei a trabalhar com o #72, percebi que os testes no Travis CI do projeto falhavam sem motivo, e outras vezes, não, causando resultados como este:

![travis](http://imgh.us/nao-determinismo-junit-test-travis-ci-passing-failing.png)

**Causa do bug:** Comparação de dois objetos do tipo `java.util.Date` que **ocasionalmente** é considerada como **falsa** pelo JUnit, mesmo sendo datas iguais. `java.util.Date` para começar, é *depreciada*[⁽¹⁾](http://docs.oracle.com/javase/8/docs/api/java/util/Date.html#Date-int-int-int-) e complexa (tem muitas variáveis e objetos dentro de objetos em sua implementação[⁽²⁾](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/util/Date.java)). Isso causa mensagens de erro como esta:

```
Failed tests:   TestConsultaPredefinidaComParametrosMultiplosComSucesso(br.ufg.inf.servico.ExecConsTest): 
expected: java.util.Date<Thu Oct 27 01:02:51 UTC 2016>
but was:  java.util.Date<Thu Oct 27 01:02:51 UTC 2016>
```

**Possíveis soluções para o problema:**

 * Usar ou implementar (*override*) a função `toString()` da classe, ou similares, que retorne um `String` "formatado" e o use para comparar no `assertEquals(...);`. Assim sempre dará certo, independentente do Java ou o PC que estiver sendo usado, ou qualquer outro motivo.
 * Usar `Calendar` ou `GregorianCalendar` ao invés de `Date` (recomendado pelo @marceloquinta);
 * Implementar (fazer *override*) do método `equals()` da classe[⁽⁴⁾](http://javarevisited.blogspot.com.br/2011/02/how-to-write-equals-method-in-java.html)
 * Fazer `AssertEquals` apenas de variáveis da classe ao invés do objeto inteiro (mais viável, na minha opinião).

**Comment by gabrielaimeeg** [comment]
Criada branch "G1-Anomalia-ExecCons" para a correção do problema.
